language: php

php:
  - 5.6

env:
  - PS_VERSION="1.6.1.1"
  #- PS_VERSION="1.6.0.1"
  #- PS_VERSION="1.5.6.2"
  #- PS_VERSION="1.5.4.1"

matrix:
  fast_finish: true
  allow_failures:
    - env: PS_VERSION="1.5.4.1"


before_install:
  - sudo apt-get update
  - sudo apt-get install rsync


before_script:
  - sh ./tests/setup/apache.sh
  - sh ./tests/setup/prestashop.sh
  - sudo chmod -R 777 /var/www
  - rsync -a ${TRAVIS_BUILD_DIR}/ /var/www/PS_${PS_VERSION}/modules/zzcleanurls/


script:
  - grep '#   v1.' /var/www/PS_${PS_VERSION}/docs/CHANGELOG.txt | head -1
  - grep '$this->version' /var/www/PS_${PS_VERSION}/modules/zzcleanurls/zzcleanurls.php | head -1


