language: php

php:
  - 5.6

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update
  - sudo apt-get install git

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f tests/travis-ci-apache-vhost.conf /etc/apache2/sites-available/default
  - sudo mkdir -p /var/www/prestashop.test
  - sudo git archive --remote=https://github.com/PrestaShop/PrestaShop.git 1.6.1.1 | (cd /var/www/; tar x) 
  - sudo chmod 777 -R /var/www/
  - sudo service apache2 restart

script:
  - php /var/www/prestashop.test/install-dev/index_cli.php --language=en --country=us --domain=localhost --base_uri=/prestashop.test --db_name=prestashop.test --db_create=1 --name=prestashop.test --password=123456789
  - cd /var/www/prestashop.test/tests && bash getcomposer.sh && php composer.phar install 
  
