language: php

php:
  - 5.6

env:
  - PS_VERSION="1.6.1.1"
  #- PS_VERSION="1.6.0.1"
  #- PS_VERSION="1.5.6.2"
  #- PS_VERSION="1.5.4.1"

matrix:
  fast_finish: true
  allow_failures:
    - env: PS_VERSION="1.5.4.1"

before_install:
  - sudo apt-get update
  - sudo apt-get install rsync

before_script:
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'date.timezone = "Europe/Rome"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f tests/travis-ci-apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s#%DOC_ROOT_DIR%#/var/www/PS_${PS_VERSION}#g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  # setup PrestaShop
  - sudo git clone --single-branch --branch ${PS_VERSION}  https://github.com/PrestaShop/PrestaShop.git /var/www/PS_${PS_VERSION}
  - php /var/www/PS_${PS_VERSION}/install-dev/index_cli.php --language=en --country=us --domain=localhost --base_uri=/prestashop.test --db_name=prestashop.test --db_create=1 --name=prestashop.test --password=123456789
  # install our module
  - sudo chmod -R 777 /var/www
  - rsync -a  ${TRAVIS_BUILD_DIR}/ /var/www/PS_${PS_VERSION}/modules/zzcleanurls/

script:
  - cd /var/www/PS_${PS_VERSION}/
  - grep '#   v1.' ./docs/CHANGELOG.txt | head -1
  - grep -i 'version' ./modules/zzcleanurls/zzcleanurls.php | head -1


